export const persons = [
  {
    photo: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "María Hernández",
    age: 25,
    location: "Suba",
    service_eight: 75000,
    service_four: 58000,
    description: "Especialista en limpieza de hogares y oficinas, con 5 años de experiencia.",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Laura Cárdenas",
    age: 32,
    location: "Chapinero",
    service_eight: 80000,
    service_four: 60000,
    description: "Responsable, puntual y con excelente atención al detalle.",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/30.jpg",
    name: "Andrea Ramírez",
    age: 45,
    location: "Engativá",
    service_eight: 70000,
    service_four: 55000,
    description: "Amplia experiencia en limpieza profunda y desinfección.",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/40.jpg",
    name: "Diana Torres",
    age: 38,
    location: "Usaquén",
    service_eight: 82000,
    service_four: 61000,
    description: "Confiable y dedicada, recomendada por clientes frecuentes.",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/50.jpg",
    name: "Sandra Gómez",
    age: 29,
    location: "Bosa",
    service_eight: 68000,
    service_four: 53000,
    description: "Especialista en limpieza ecológica y productos amigables.",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/60.jpg",
    name: "Paula Jiménez",
    age: 41,
    location: "Kennedy",
    service_eight: 77000,
    service_four: 59000,
    description: "Experta en organización y aseo de espacios grandes.",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/70.jpg",
    name: "Camila Rincón",
    age: 35,
    location: "Fontibón",
    service_eight: 75000,
    service_four: 58000,
    description: "Amable, eficiente y con referencias verificables.",
  },
  {
    photo: "https://randomuser.me/api/portraits/women/80.jpg",
    name: "Natalia Vargas",
    age: 47,
    location: "Teusaquillo",
    service_eight: 79000,
    service_four: 60000,
    description: "Más de 10 años de experiencia en servicios de aseo.",
  },
];
