export const persons = [
  {
    photo: "https://thispersondoesnotexist.com/",
    name: "María Hernández",
    age: 25,
    location: "suba",
    service_eight: 75000,
    service_four: 58000,
  },
  {
    photo: "https://thispersondoesnotexist.com/",
    name: "Laura Cárdenas",
    age: 32,
    location: "chapinero",
    service_eight: 80000,
    service_four: 60000,
  },
  {
    photo: "https://thispersondoesnotexist.com/",
    name: "Andrea Ramírez",
    age: 45,
    location: "engativá",
    service_eight: 70000,
    service_four: 55000,
  },
  {
    photo: "https://thispersondoesnotexist.com/",
    name: "Diana Torres",
    age: 38,
    location: "usaquén",
    service_eight: 82000,
    service_four: 61000,
  },
  {
    photo: "https://thispersondoesnotexist.com/",
    name: "Sandra Gómez",
    age: 29,
    location: "bosa",
    service_eight: 68000,
    service_four: 53000,
  },
  {
    photo: "https://thispersondoesnotexist.com/",
    name: "Paula Jiménez",
    age: 41,
    location: "kennedy",
    service_eight: 77000,
    service_four: 59000,
  },
  {
    photo: "https://thispersondoesnotexist.com/",
    name: "Camila Rincón",
    age: 35,
    location: "fontibón",
    service_eight: 75000,
    service_four: 58000,
  },
  {
    photo: "https://thispersondoesnotexist.com/",
    name: "Natalia Vargas",
    age: 47,
    location: "teusaquillo",
    service_eight: 79000,
    service_four: 60000,
  },
];
